export CUDA_VISIBLE_DEVICES=4
MODEL_NAME='ft-BI-en_syn-hi_syn-small-extended-en'
# TASK_NAME='CoLA'
# NUM_CLASSES=1
# BATCH_SIZE=48
# EPOCHS=30
# python3 classification.py $MODEL_NAME $TASK_NAME $NUM_CLASSES $BATCH_SIZE $EPOCHS
# TASK_NAME='mnli_matched'
# NUM_CLASSES=3
# BATCH_SIZE=48
# EPOCHS=5
# python3 classification.py $MODEL_NAME $TASK_NAME $NUM_CLASSES $BATCH_SIZE $EPOCHS
TASK_NAME='mnli_mismatched'
NUM_CLASSES=3
BATCH_SIZE=48
EPOCHS=5
python3 classification.py $MODEL_NAME $TASK_NAME $NUM_CLASSES $BATCH_SIZE $EPOCHS
TASK_NAME='mrpc'
NUM_CLASSES=1
BATCH_SIZE=48
EPOCHS=30
python3 classification.py $MODEL_NAME $TASK_NAME $NUM_CLASSES $BATCH_SIZE $EPOCHS
TASK_NAME='qnli'
NUM_CLASSES=1
BATCH_SIZE=48
EPOCHS=10
python3 classification.py $MODEL_NAME $TASK_NAME $NUM_CLASSES $BATCH_SIZE $EPOCHS
TASK_NAME='qqp'
NUM_CLASSES=1
BATCH_SIZE=48
EPOCHS=5
python3 classification.py $MODEL_NAME $TASK_NAME $NUM_CLASSES $BATCH_SIZE $EPOCHS
TASK_NAME='rte'
NUM_CLASSES=1
BATCH_SIZE=48
EPOCHS=30
python3 classification.py $MODEL_NAME $TASK_NAME $NUM_CLASSES $BATCH_SIZE $EPOCHS
TASK_NAME='sst2'
NUM_CLASSES=1
BATCH_SIZE=48
EPOCHS=10
python3 classification.py $MODEL_NAME $TASK_NAME $NUM_CLASSES $BATCH_SIZE $EPOCHS
TASK_NAME='wnli'
NUM_CLASSES=1
BATCH_SIZE=48
EPOCHS=50
python3 classification.py $MODEL_NAME $TASK_NAME $NUM_CLASSES $BATCH_SIZE $EPOCHS
TASK_NAME='paws-x'
NUM_CLASSES=1
BATCH_SIZE=48
EPOCHS=10
python3 classification.py $MODEL_NAME $TASK_NAME $NUM_CLASSES $BATCH_SIZE $EPOCHS