export CUDA_VISIBLE_DEVICES=7
MODEL_NAME='ft-syn-hi-small-extended-syn-hi'
# TASK_NAME='indicxnli'
# NUM_CLASSES=3
# BATCH_SIZE=48
# EPOCHS=5
# python3 classification_indic.py $MODEL_NAME $TASK_NAME $NUM_CLASSES $BATCH_SIZE $EPOCHS
TASK_NAME='bbca.hi'
NUM_CLASSES=14
BATCH_SIZE=24
EPOCHS=20
CONTEXT_LEN=1024
python3 classification_indic.py $MODEL_NAME $TASK_NAME $NUM_CLASSES $BATCH_SIZE $EPOCHS $CONTEXT_LEN
TASK_NAME='iitp-mr.hi'
NUM_CLASSES=3
BATCH_SIZE=24
EPOCHS=20
CONTEXT_LEN=1024
python3 classification_indic.py $MODEL_NAME $TASK_NAME $NUM_CLASSES $BATCH_SIZE $EPOCHS $CONTEXT_LEN
TASK_NAME='iitp-pr.hi'
NUM_CLASSES=3
BATCH_SIZE=48
EPOCHS=20
CONTEXT_LEN=128
python3 classification_indic.py $MODEL_NAME $TASK_NAME $NUM_CLASSES $BATCH_SIZE $EPOCHS $CONTEXT_LEN
TASK_NAME='md.hi'
NUM_CLASSES=6
BATCH_SIZE=48
EPOCHS=20
CONTEXT_LEN=128
python3 classification_indic.py $MODEL_NAME $TASK_NAME $NUM_CLASSES $BATCH_SIZE $EPOCHS $CONTEXT_LEN
